INSERT INTO master_countries (name, iso_code) VALUES ('Andorra','ad');
INSERT INTO master_countries (name, iso_code) VALUES ('United Arab Emirates','ae');
INSERT INTO master_countries (name, iso_code) VALUES ('Afghanistan','af');
INSERT INTO master_countries (name, iso_code) VALUES ('Antigua and Barbuda','ag');
INSERT INTO master_countries (name, iso_code) VALUES ('Anguilla','ai');
INSERT INTO master_countries (name, iso_code) VALUES ('Albania','al');
INSERT INTO master_countries (name, iso_code) VALUES ('Armenia','am');
INSERT INTO master_countries (name, iso_code) VALUES ('Netherlands Antilles','an');
INSERT INTO master_countries (name, iso_code) VALUES ('Angola','ao');
INSERT INTO master_countries (name, iso_code) VALUES ('Antarctica','aq');
INSERT INTO master_countries (name, iso_code) VALUES ('Argentina','ar');
INSERT INTO master_countries (name, iso_code) VALUES ('American Samoa','as');
INSERT INTO master_countries (name, iso_code) VALUES ('Austria','at');
INSERT INTO master_countries (name, iso_code) VALUES ('Australia','au');
INSERT INTO master_countries (name, iso_code) VALUES ('Aruba','aw');
INSERT INTO master_countries (name, iso_code) VALUES ('Åland Islands','ax');
INSERT INTO master_countries (name, iso_code) VALUES ('Azerbaijan','az');
INSERT INTO master_countries (name, iso_code) VALUES ('Bosnia and Herzegovina','ba');
INSERT INTO master_countries (name, iso_code) VALUES ('Barbados','bb');
INSERT INTO master_countries (name, iso_code) VALUES ('Bangladesh','bd');
INSERT INTO master_countries (name, iso_code) VALUES ('Belgium','be');
INSERT INTO master_countries (name, iso_code) VALUES ('Burkina Faso','bf');
INSERT INTO master_countries (name, iso_code) VALUES ('Bulgaria','bg');
INSERT INTO master_countries (name, iso_code) VALUES ('Bahrain','bh');
INSERT INTO master_countries (name, iso_code) VALUES ('Burundi','bi');
INSERT INTO master_countries (name, iso_code) VALUES ('Benin','bj');
INSERT INTO master_countries (name, iso_code) VALUES ('Saint Barthélemy','bl');
INSERT INTO master_countries (name, iso_code) VALUES ('Bermuda','bm');
INSERT INTO master_countries (name, iso_code) VALUES ('Brunei Darussalam','bn');
INSERT INTO master_countries (name, iso_code) VALUES ('Bolivia','bo');
INSERT INTO master_countries (name, iso_code) VALUES ('Bonaire, Sint Eustatius and Saba','bq');
INSERT INTO master_countries (name, iso_code) VALUES ('Brazil','br');
INSERT INTO master_countries (name, iso_code) VALUES ('Bahamas','bs');
INSERT INTO master_countries (name, iso_code) VALUES ('Bhutan','bt');
INSERT INTO master_countries (name, iso_code) VALUES ('Bouvet Island','bv');
INSERT INTO master_countries (name, iso_code) VALUES ('Botswana','bvv');
INSERT INTO master_countries (name, iso_code) VALUES ('Belarus','by');
INSERT INTO master_countries (name, iso_code) VALUES ('Belize','bz');
INSERT INTO master_countries (name, iso_code) VALUES ('Canada','ca');
INSERT INTO master_countries (name, iso_code) VALUES ('Cocos Islands','cc');
INSERT INTO master_countries (name, iso_code) VALUES ('congo','cg');
INSERT INTO master_countries (name, iso_code) VALUES ('Central African Republic','cf');
INSERT INTO master_countries (name, iso_code) VALUES ('Switzerland','ch');
INSERT INTO master_countries (name, iso_code) VALUES ('Côte DIvoire','ci');
INSERT INTO master_countries (name, iso_code) VALUES ('Cook Islands','ck');
INSERT INTO master_countries (name, iso_code) VALUES ('Chile','cl');
INSERT INTO master_countries (name, iso_code) VALUES ('Cameroon','cm');
INSERT INTO master_countries (name, iso_code) VALUES ('China','cn');
INSERT INTO master_countries (name, iso_code) VALUES ('Colombia','co');
INSERT INTO master_countries (name, iso_code) VALUES ('Costa Rica','cr');
INSERT INTO master_countries (name, iso_code) VALUES ('cuba','cu');
INSERT INTO master_countries (name, iso_code) VALUES ('Cape Verde','cv');
INSERT INTO master_countries (name, iso_code) VALUES ('Curaçao','cw');
INSERT INTO master_countries (name, iso_code) VALUES ('Christmas Island','cx');
INSERT INTO master_countries (name, iso_code) VALUES ('Cyprus','cy');
INSERT INTO master_countries (name, iso_code) VALUES ('Czech Republic','cz');
INSERT INTO master_countries (name, iso_code) VALUES ('Germany','de');
INSERT INTO master_countries (name, iso_code) VALUES ('Denmark','dk');
INSERT INTO master_countries (name, iso_code) VALUES ('Dominican Republic','do');
INSERT INTO master_countries (name, iso_code) VALUES ('Algeria','dz');
INSERT INTO master_countries (name, iso_code) VALUES ('Ecuador','ec');
INSERT INTO master_countries (name, iso_code) VALUES ('Egypt','eg');
INSERT INTO master_countries (name, iso_code) VALUES ('Spain','es');
INSERT INTO master_countries (name, iso_code) VALUES ('Finland','fi');
INSERT INTO master_countries (name, iso_code) VALUES ('Fiji','fj');
INSERT INTO master_countries (name, iso_code) VALUES ('France','fr');
INSERT INTO master_countries (name, iso_code) VALUES ('United Kingdom','gb');
INSERT INTO master_countries (name, iso_code) VALUES ('Georgia','ge');
INSERT INTO master_countries (name, iso_code) VALUES ('French Guiana','gf');
INSERT INTO master_countries (name, iso_code) VALUES ('Ghana','gh');
INSERT INTO master_countries (name, iso_code) VALUES ('Greenland','gl');
INSERT INTO master_countries (name, iso_code) VALUES ('Gambia','gm');
INSERT INTO master_countries (name, iso_code) VALUES ('Guinea','gn');
INSERT INTO master_countries (name, iso_code) VALUES ('Greece','gr');
INSERT INTO master_countries (name, iso_code) VALUES ('Hong Kong','hk');
INSERT INTO master_countries (name, iso_code) VALUES ('Croatia','hr');
INSERT INTO master_countries (name, iso_code) VALUES ('Hungary','hu');
INSERT INTO master_countries (name, iso_code) VALUES ('Indonesia','id');
INSERT INTO master_countries (name, iso_code) VALUES ('Ireland','ie');
INSERT INTO master_countries (name, iso_code) VALUES ('Israel','il');
INSERT INTO master_countries (name, iso_code) VALUES ('India','in');
INSERT INTO master_countries (name, iso_code) VALUES ('Iraq','iq');
INSERT INTO master_countries (name, iso_code) VALUES ('iran','ir');
INSERT INTO master_countries (name, iso_code) VALUES ('Iceland','is');
INSERT INTO master_countries (name, iso_code) VALUES ('Italy','it');
INSERT INTO master_countries (name, iso_code) VALUES ('Jersey','je');
INSERT INTO master_countries (name, iso_code) VALUES ('Jamaica','jm');
INSERT INTO master_countries (name, iso_code) VALUES ('Jordan','jo');
INSERT INTO master_countries (name, iso_code) VALUES ('Japan','jp');
INSERT INTO master_countries (name, iso_code) VALUES ('Kenya','ke');
INSERT INTO master_countries (name, iso_code) VALUES ('Lebanon','lb');
INSERT INTO master_countries (name, iso_code) VALUES ('Kazakhstan','kz');
INSERT INTO master_countries (name, iso_code) VALUES ('Kuwait','kw');
INSERT INTO master_countries (name, iso_code) VALUES ('Korea','kr');
INSERT INTO master_countries (name, iso_code) VALUES ('Liberia','lr');
INSERT INTO master_countries (name, iso_code) VALUES ('Sri Lanka','lk');
INSERT INTO master_countries (name, iso_code) VALUES ('Libya','ly');
INSERT INTO master_countries (name, iso_code) VALUES ('Morocco','ma');
INSERT INTO master_countries (name, iso_code) VALUES ('Macao','mo');
INSERT INTO master_countries (name, iso_code) VALUES ('Myanmar','mm');
INSERT INTO master_countries (name, iso_code) VALUES ('Mauritius','mu');
INSERT INTO master_countries (name, iso_code) VALUES ('Maldives','mv');
INSERT INTO master_countries (name, iso_code) VALUES ('Mexico','mx');
INSERT INTO master_countries (name, iso_code) VALUES ('Malaysia','my');
INSERT INTO master_countries (name, iso_code) VALUES ('Mozambique','mz');
INSERT INTO master_countries (name, iso_code) VALUES ('Namibia','na');
INSERT INTO master_countries (name, iso_code) VALUES ('Niger','ne');
INSERT INTO master_countries (name, iso_code) VALUES ('Nepal','np');
INSERT INTO master_countries (name, iso_code) VALUES ('Norway','no');
INSERT INTO master_countries (name, iso_code) VALUES ('Netherlands','nl');
INSERT INTO master_countries (name, iso_code) VALUES ('Nigeria','ng');
INSERT INTO master_countries (name, iso_code) VALUES ('New Zealand','nz');
INSERT INTO master_countries (name, iso_code) VALUES ('Oman','om');
INSERT INTO master_countries (name, iso_code) VALUES ('Peru','pe');
INSERT INTO master_countries (name, iso_code) VALUES ('Poland','pl');
INSERT INTO master_countries (name, iso_code) VALUES ('Pakistan','pk');
INSERT INTO master_countries (name, iso_code) VALUES ('Philippines','ph');
INSERT INTO master_countries (name, iso_code) VALUES ('Papua New Guinea','pg');
INSERT INTO master_countries (name, iso_code) VALUES ('Portugal','pt');
INSERT INTO master_countries (name, iso_code) VALUES ('Paraguay','py');
INSERT INTO master_countries (name, iso_code) VALUES ('Puerto Rico','pr');
INSERT INTO master_countries (name, iso_code) VALUES ('Qatar','qa');
INSERT INTO master_countries (name, iso_code) VALUES ('Singapore','sg');
INSERT INTO master_countries (name, iso_code) VALUES ('Sweden','se');
INSERT INTO master_countries (name, iso_code) VALUES ('Sudan','sd');
INSERT INTO master_countries (name, iso_code) VALUES ('Saudi Arabia','sa');
INSERT INTO master_countries (name, iso_code) VALUES ('Slovakia','sk');
INSERT INTO master_countries (name, iso_code) VALUES ('Somalia','so');
INSERT INTO master_countries (name, iso_code) VALUES ('Thailand','th');
INSERT INTO master_countries (name, iso_code) VALUES ('Trinidad and Tobago','tt');
INSERT INTO master_countries (name, iso_code) VALUES ('Turkey','tr');
INSERT INTO master_countries (name, iso_code) VALUES ('Ukraine','ua');
INSERT INTO master_countries (name, iso_code) VALUES ('Uganda','ug');
INSERT INTO master_countries (name, iso_code) VALUES ('United States','us');
INSERT INTO master_countries (name, iso_code) VALUES ('Uruguay','uy');
INSERT INTO master_countries (name, iso_code) VALUES ('Uzbekistan','uz');
INSERT INTO master_countries (name, iso_code) VALUES ('Yemen','ye');
INSERT INTO master_countries (name, iso_code) VALUES ('Vietnam','vn');
INSERT INTO master_countries (name, iso_code) VALUES ('Zimbabwe','zw');



INSERT INTO master_platforms (name) VALUES ('TWITCH'),
				            ('YOUTUBE'),
				            ('FACEBOOK'),
				            ('MIXER'),
				            ('PERISCOPE'),
				            ('VIMEO'),
				            ('YOUNOW'),
				            ('YACAST'),
				            ('RESTREAM'),
				            ('BRIGHTCOVE');
